/* SCE CONFIDENTIAL
 * PlayStation(R)Vita Programmer Tool Runtime Library Release 02.000.081
 * Copyright (C) 2010 Sony Computer Entertainment Inc. 
 * All Rights Reserved.
 */

uniform float4x4 wvp;
uniform float4x4 localToWorld;

void main(
	float3 aPosition,
	float4 out vPosition : POSITION,
	float2 out vTexCoord : TEXCOORD0)
{
	
	vPosition = mul(mul(float4(aPosition, 1.f), localToWorld), wvp);
	vTexCoord.x = 0.5f;
	vTexCoord.y = 0.5f;
}
